sensors:
  - air_density
  - air_temperature
  - voltage_air
  - battery_air
  - voltage_sky
  - battery_sky
  - voltage_tempest
  - battery_tempest
  - battery_mode # Only for Tempest Devices
  - beaufort
  - dewpoint
  - dewpoint_description
  - delta_t
  - feelslike
  - illuminance
  - lightning_strike_count
  - lightning_strike_count_1hr
  - lightning_strike_count_3hr
  - lightning_strike_count_today
  - lightning_strike_distance
  - lightning_strike_energy
  - lightning_strike_time
  - precipitation_type
  - pressure_trend
  - rain_intensity
  - rain_rate
  - rain_start_time
  - rain_today
  - rain_yesterday
  - rain_duration_today
  - rain_duration_yesterday
  - relative_humidity
  - sealevel_pressure
  - solar_radiation
  - station_pressure
  - temperature_description
  - uptime
  - uv
  - uv_description
  - visibility
  - wetbulb
  - wet_bulb_globe_temperature
  - wind_bearing
  - wind_bearing_avg
  - wind_direction
  - wind_direction_avg
  - wind_gust
  - wind_lull
  - wind_speed
  - wind_speed_avg
  - weather
  