 sensors:
  - absolute_humidity
  - air_status
  - air_temperature
  - battery
  - battery_air
  - battery_level_air
  - battery_level_sky
  - beaufort
  - dewpoint
  - dewpoint_description
  - delta_t
  - feelslike
  - hub_status
  - illuminance
  - lightning_strike_count
  - lightning_strike_count_1hr
  - lightning_strike_count_3hr
  - lightning_strike_count_today
  - lightning_strike_distance
  - lightning_strike_energy
  - lightning_strike_time
  - precipitation_type
  - pressure_trend
  - rain_intensity
  - rain_rate
  - rain_start_time
  - rain_today
  - rain_yesterday
  - rain_duration_today
  - rain_duration_yesterday
  - relative_humidity
  - sealevel_pressure
  - sky_status
  - solar_radiation
  - station_pressure
  - temperature_description
  - uv
  - uv_description
  - visibility
  - wetbulb
  - wbgt #wet_bulb_globe_temperature
  - wind_bearing
  - wind_bearing_avg
  - wind_direction
  - wind_direction_avg
  - wind_gust
  - wind_lull
  - wind_speed
  - wind_speed_avg
  - weather # Only if you are loading the Forecast
